version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-init:
    image: postgres:17-alpine
    volumes:
      - ./scripts:/scripts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    entrypoint: []
    command: >
      bash -c "
        echo 'Waiting for postgres...' &&
        while ! pg_isready -h postgres -U postgres; do
          sleep 1;
        done &&
        echo 'PostgreSQL is ready!' &&
        chmod +x /scripts/init-db.sh &&
        /scripts/init-db.sh"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
