/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MailIndexImport } from './routes/$mail/index'
import { Route as LoginLayoutImport } from './routes/login/_layout'
import { Route as LoginLayoutIndexImport } from './routes/login/_layout.index'

// Create Virtual Routes

const LoginImport = createFileRoute('/login')()
const DebugLazyImport = createFileRoute('/debug')()
const IndexLazyImport = createFileRoute('/')()
const LoginLayoutCreateLazyImport = createFileRoute('/login/_layout/create')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DebugLazyRoute = DebugLazyImport.update({
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/debug.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MailIndexRoute = MailIndexImport.update({
  path: '/$mail/',
  getParentRoute: () => rootRoute,
} as any)

const LoginLayoutRoute = LoginLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LoginRoute,
} as any)

const LoginLayoutIndexRoute = LoginLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LoginLayoutRoute,
} as any)

const LoginLayoutCreateLazyRoute = LoginLayoutCreateLazyImport.update({
  path: '/create',
  getParentRoute: () => LoginLayoutRoute,
} as any).lazy(() =>
  import('./routes/login/_layout.create.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/login/_layout': {
      id: '/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLayoutImport
      parentRoute: typeof LoginRoute
    }
    '/$mail/': {
      id: '/$mail/'
      path: '/$mail'
      fullPath: '/$mail'
      preLoaderRoute: typeof MailIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/_layout/create': {
      id: '/login/_layout/create'
      path: '/create'
      fullPath: '/login/create'
      preLoaderRoute: typeof LoginLayoutCreateLazyImport
      parentRoute: typeof LoginLayoutImport
    }
    '/login/_layout/': {
      id: '/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginLayoutIndexImport
      parentRoute: typeof LoginLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  DebugLazyRoute,
  LoginRoute: LoginRoute.addChildren({
    LoginLayoutRoute: LoginLayoutRoute.addChildren({
      LoginLayoutCreateLazyRoute,
      LoginLayoutIndexRoute,
    }),
  }),
  MailIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/debug",
        "/login",
        "/$mail/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/debug": {
      "filePath": "debug.lazy.tsx"
    },
    "/login": {
      "filePath": "login",
      "children": [
        "/login/_layout"
      ]
    },
    "/login/_layout": {
      "filePath": "login/_layout.tsx",
      "parent": "/login",
      "children": [
        "/login/_layout/create",
        "/login/_layout/"
      ]
    },
    "/$mail/": {
      "filePath": "$mail/index.tsx"
    },
    "/login/_layout/create": {
      "filePath": "login/_layout.create.lazy.tsx",
      "parent": "/login/_layout"
    },
    "/login/_layout/": {
      "filePath": "login/_layout.index.tsx",
      "parent": "/login/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
