/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MailIndexImport } from './routes/$mail/index'
import { Route as LoginLayoutImport } from './routes/login/_layout'
import { Route as ConfigureLayoutImport } from './routes/configure/_layout'
import { Route as LoginLayoutIndexImport } from './routes/login/_layout.index'
import { Route as ConfigureLayoutIndexImport } from './routes/configure/_layout.index'
import { Route as LoginLayoutCallbackImport } from './routes/login/_layout.callback'
import { Route as ConfigureLayoutInstanceIndexImport } from './routes/configure/_layout.instance/index'
import { Route as ConfigureLayoutInstanceHealthcheckImport } from './routes/configure/_layout.instance/healthcheck'

// Create Virtual Routes

const LoginImport = createFileRoute('/login')()
const ConfigureImport = createFileRoute('/configure')()
const DebugLazyImport = createFileRoute('/debug')()
const IndexLazyImport = createFileRoute('/')()
const LoginLayoutCreateLazyImport = createFileRoute('/login/_layout/create')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ConfigureRoute = ConfigureImport.update({
  path: '/configure',
  getParentRoute: () => rootRoute,
} as any)

const DebugLazyRoute = DebugLazyImport.update({
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/debug.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MailIndexRoute = MailIndexImport.update({
  path: '/$mail/',
  getParentRoute: () => rootRoute,
} as any)

const LoginLayoutRoute = LoginLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LoginRoute,
} as any)

const ConfigureLayoutRoute = ConfigureLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => ConfigureRoute,
} as any)

const LoginLayoutIndexRoute = LoginLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LoginLayoutRoute,
} as any)

const ConfigureLayoutIndexRoute = ConfigureLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => ConfigureLayoutRoute,
} as any)

const LoginLayoutCreateLazyRoute = LoginLayoutCreateLazyImport.update({
  path: '/create',
  getParentRoute: () => LoginLayoutRoute,
} as any).lazy(() =>
  import('./routes/login/_layout.create.lazy').then((d) => d.Route),
)

const LoginLayoutCallbackRoute = LoginLayoutCallbackImport.update({
  path: '/callback',
  getParentRoute: () => LoginLayoutRoute,
} as any)

const ConfigureLayoutInstanceIndexRoute =
  ConfigureLayoutInstanceIndexImport.update({
    path: '/instance/',
    getParentRoute: () => ConfigureLayoutRoute,
  } as any)

const ConfigureLayoutInstanceHealthcheckRoute =
  ConfigureLayoutInstanceHealthcheckImport.update({
    path: '/instance/healthcheck',
    getParentRoute: () => ConfigureLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugLazyImport
      parentRoute: typeof rootRoute
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureImport
      parentRoute: typeof rootRoute
    }
    '/configure/_layout': {
      id: '/configure/_layout'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureLayoutImport
      parentRoute: typeof ConfigureRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/login/_layout': {
      id: '/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLayoutImport
      parentRoute: typeof LoginRoute
    }
    '/$mail/': {
      id: '/$mail/'
      path: '/$mail'
      fullPath: '/$mail'
      preLoaderRoute: typeof MailIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/_layout/callback': {
      id: '/login/_layout/callback'
      path: '/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginLayoutCallbackImport
      parentRoute: typeof LoginLayoutImport
    }
    '/login/_layout/create': {
      id: '/login/_layout/create'
      path: '/create'
      fullPath: '/login/create'
      preLoaderRoute: typeof LoginLayoutCreateLazyImport
      parentRoute: typeof LoginLayoutImport
    }
    '/configure/_layout/': {
      id: '/configure/_layout/'
      path: '/'
      fullPath: '/configure/'
      preLoaderRoute: typeof ConfigureLayoutIndexImport
      parentRoute: typeof ConfigureLayoutImport
    }
    '/login/_layout/': {
      id: '/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginLayoutIndexImport
      parentRoute: typeof LoginLayoutImport
    }
    '/configure/_layout/instance/healthcheck': {
      id: '/configure/_layout/instance/healthcheck'
      path: '/instance/healthcheck'
      fullPath: '/configure/instance/healthcheck'
      preLoaderRoute: typeof ConfigureLayoutInstanceHealthcheckImport
      parentRoute: typeof ConfigureLayoutImport
    }
    '/configure/_layout/instance/': {
      id: '/configure/_layout/instance/'
      path: '/instance'
      fullPath: '/configure/instance'
      preLoaderRoute: typeof ConfigureLayoutInstanceIndexImport
      parentRoute: typeof ConfigureLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  DebugLazyRoute,
  ConfigureRoute: ConfigureRoute.addChildren({
    ConfigureLayoutRoute: ConfigureLayoutRoute.addChildren({
      ConfigureLayoutIndexRoute,
      ConfigureLayoutInstanceHealthcheckRoute,
      ConfigureLayoutInstanceIndexRoute,
    }),
  }),
  LoginRoute: LoginRoute.addChildren({
    LoginLayoutRoute: LoginLayoutRoute.addChildren({
      LoginLayoutCallbackRoute,
      LoginLayoutCreateLazyRoute,
      LoginLayoutIndexRoute,
    }),
  }),
  MailIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/debug",
        "/configure",
        "/login",
        "/$mail/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/debug": {
      "filePath": "debug.lazy.tsx"
    },
    "/configure": {
      "filePath": "configure",
      "children": [
        "/configure/_layout"
      ]
    },
    "/configure/_layout": {
      "filePath": "configure/_layout.tsx",
      "parent": "/configure",
      "children": [
        "/configure/_layout/",
        "/configure/_layout/instance/healthcheck",
        "/configure/_layout/instance/"
      ]
    },
    "/login": {
      "filePath": "login",
      "children": [
        "/login/_layout"
      ]
    },
    "/login/_layout": {
      "filePath": "login/_layout.tsx",
      "parent": "/login",
      "children": [
        "/login/_layout/callback",
        "/login/_layout/create",
        "/login/_layout/"
      ]
    },
    "/$mail/": {
      "filePath": "$mail/index.tsx"
    },
    "/login/_layout/callback": {
      "filePath": "login/_layout.callback.tsx",
      "parent": "/login/_layout"
    },
    "/login/_layout/create": {
      "filePath": "login/_layout.create.lazy.tsx",
      "parent": "/login/_layout"
    },
    "/configure/_layout/": {
      "filePath": "configure/_layout.index.tsx",
      "parent": "/configure/_layout"
    },
    "/login/_layout/": {
      "filePath": "login/_layout.index.tsx",
      "parent": "/login/_layout"
    },
    "/configure/_layout/instance/healthcheck": {
      "filePath": "configure/_layout.instance/healthcheck.tsx",
      "parent": "/configure/_layout"
    },
    "/configure/_layout/instance/": {
      "filePath": "configure/_layout.instance/index.tsx",
      "parent": "/configure/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
